FROM confluentinc/cp-kafka-connect-base:7.8.0

USER root

# Install necessary utilities
RUN apt-get update && apt-get install -y curl netcat

# Copy the confluent classes
COPY --from=confluentinc/cp-server-connect:7.8.0 /usr/share/java/confluent-common /usr/share/java/confluent-common

USER appuser

ENV CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/confluent-hub-components"